apiVersion: v1
kind: Service
metadata:
  name: fileserver
  namespace: velero
spec:
  ports:
    - name: fileserver
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app.kubernetes.io/instance: velero
    app.kubernetes.io/name: velero
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
