apiVersion: v1
kind: ConfigMap
metadata:
  name: local-volume-provider-config
  namespace: velero
  labels:
    velero.io/plugin-config: ""
    replicated.com/nfs: ObjectStore
    replicated.com/hostpath: ObjectStore
data:
  fileserverImage: ttl.sh/dans/local-volume-provider:12h
  securityContextRunAsUser: "1001"
  securityContextFsGroup: "1001"
  # use this if you deployed an ingress for the fileserver running on 3000 to access logs from outside the cluster network
  # e.g. via ur velero cli. You will need to deploy the service/ingress yourself. See examples/filserverService.yaml
  externalDownloadHostname: "www.velero-logs.domain.com"
  # using https currently seems not to be supported by the velero client
  externalDownloadScheme: "http"
  externalDownloadPort: 80
